test a bunch of stuff from ./test

diff --git a/scons/test b/scons/test
--- a/scons/test
+++ b/scons/test
@@ -3,15 +3,15 @@ set -eu
 top="$(pwd)"
 log_path="${top}/test.log"
 ./clean
-for d in */; do
-  cd "${top}/${d}"
-  if [ -e test ]; then
-    echo "$d"
-    ret=0
-    ./test >> "$log_path" 2>&1 || ret=$?
-    if [ $? -ne 0 ]; then
-      echo "Test failed: ${d}"
-    fi
+ls -d */ | parallel "$@" --will-cite "
+cd '${top}/{}'
+if [ -e test ]; then
+  echo '{}'
+  ret=0
+  ./test >> '$log_path' 2>&1 || ret=$?
+  if [ $? -ne 0 ]; then
+    echo 'Test failed: {}'
   fi
-done
+fi
+"
 echo 'All tests passed'
diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,17 +1,46 @@
 #!/usr/bin/env bash
+
+# Test everything that is automatable.
+
 top="$(pwd)"
+
+# make test
 for t in \
     c \
+    c/extern \
+    c/static/function \
+    c/static/variable \
     cpp \
+    cpp/extern_const \
+    cpp/inline_variable \
     gcc \
     glibc \
+    linker/incremental-link \
+    linker/variable-address \
     posix \
   ; do
-  if ! make -C "$t" test; then
+  if ! make -C "$t" -j`nproc` test; then
     echo "TEST FAILED: $t"
     exit 1
   fi
 done
+
+# make only
+for t in \
+    c/interactive \
+    cpp/interactive \
+    glibc/interactive \
+    posix/curses \
+    posix/interactive \
+    posix/socket \
+  ; do
+  if ! make -C "$t" -j`nproc`; then
+    echo "TEST FAILED: $t"
+    exit 1
+  fi
+done
+
+# ./test only
 for t in \
     scons \
   ; do
